<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>testProject</title>
    <link rel="stylesheet" href="<?php echo Helper::base() ?>assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo Helper::base() ?>assets/fonts/simple-line-icons.min.css">
    <link rel="stylesheet" href="<?php echo Helper::base() ?>assets/css/styles.min.css">
</head>

<body>
    <div>
        <nav class="navbar navbar-light navbar-expand-md navigation-clean">
            <div class="container"><a class="navbar-brand" href="<?php echo Helper::base() ?>">TC Shop</a>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
                    <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navcol-1">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item" role="presentation"><a class="nav-link" href="<?php echo Helper::createLink('list');?>">Shop</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="#">Second Item</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="<?php echo Helper::createLink('cart');?>">
                            <i class="fa fa-shopping-cart" >Cart <?php if(Cart::count() > 0) echo " <span class='badge badge-pill badge-success float-right'> ". Cart::count()." </span>";?></i></a></li>
                        <li class="dropdown"><a class="dropdown-toggle nav-link dropdown-toggle" 
                            data-toggle="dropdown" aria-expanded="false" href="#">User Option</a>
                            <div class="dropdown-menu" role="menu">
                                <a class="dropdown-item" role="presentation" href="<?php echo Helper::createLink('user', ['register']);?>">Register</a>
                                <a class="dropdown-item" role="presentation" href="<?php echo Helper::createLink('user', ['login']);?>">Login</a>
                                <a class="dropdown-item" role="presentation" href="<?php echo Helper::createLink('user', ['forgot']);?>">Forgot Password</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-4 d-none d-sm-none d-md-inline d-lg-inline d-xl-inline">
                    <div class="wrapper">
                        <!-- Sidebar Holder -->
                        <nav id="sidebar">
                            <div class="sidebar-header">
                                <h3>TechCode Production</h3>
                                <strong>BS</strong>
                            </div>

                            <ul class="list-unstyled components">
                                <li class="active">
                                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">
                                        <i class="glyphicon glyphicon-home"></i>
                                        Home
                                    </a>
                                    <ul class="collapse list-unstyled" id="homeSubmenu">
                                        <li><a href="#">Home 1</a></li>
                                        <li><a href="#">Home 2</a></li>
                                        <li><a href="#">Home 3</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="glyphicon glyphicon-briefcase"></i>
                                        About
                                    </a>
                                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">
                                        <i class="glyphicon glyphicon-duplicate"></i>
                                        Pages
                                    </a>
                                    <ul class="collapse list-unstyled" id="pageSubmenu">
                                        <li><a href="#">Page 1</a></li>
                                        <li><a href="#">Page 2</a></li>
                                        <li><a href="#">Page 3</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="glyphicon glyphicon-link"></i>
                                        Portfolio
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="glyphicon glyphicon-paperclip"></i>
                                        FAQ
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="glyphicon glyphicon-send"></i>
                                        Contact
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <?php
                    require $template;

                    
                    var_dump($_SERVER);
                ?>
             </div>
        </div>
    </div>
    <script src="<?php echo Helper::base() ?>assets/js/jquery.min.js"></script>
    <script src="<?php echo Helper::base() ?>assets/bootstrap/js/bootstrap.min.js"></script>
    <!-- jQuery CDN -->
         <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
         <!-- Bootstrap Js CDN -->
         <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

         <script type="text/javascript">
             $(document).ready(function () {
                $('#sidebarCollapse').on('click', function () {
                    $('#sidebar').toggleClass('active');
                });
             });
         </script>
</body>

</html>