<?php
    function error_field($title, array $errors) {
        foreach ($errors as $error) {
            /* @var $error ValidatorError */
            if ($error->getSource() == $title) {
                return ' style="background-color:pink;"';
            }
        }
        return '';
    }
?>
<div class="row">
    <div class="col-12 offset-lg-0">
        <h1 class="text-center"><?php echo Helper::escape(ucfirst($action)) ?> Product</h1>
        <hr>
    </div>
    <div class="col-6 offset-3">
<?php if (!empty($errors)): ?>
    <ul class="errors">
        <?php foreach ($errors as $error): ?>
            <?php /* @var $error ValidationError */ ?>
            <li><?php echo $error->getMessage(); ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
        <form target="_self" method="post">
            <div class="form-group">
                <input type="text" placeholder="Name"  name="product[name]" value="<?php echo isset($pdt)?$pdt->getName() :'' ?>"
                    class="form-control"<?php echo error_field('name', $errors); ?>/></div>
            <div class="form-group">
                <input type="number" name="product[price]" min="1" placeholder="Price" 
                    value="<?php echo isset($pdt)?$pdt->getPrice() :'' ?>"
                        class="form-control" <?php echo error_field('price', $errors); ?> /></div>
            <div class="form-group">
                <textarea type="text" name="product[description]" placeholder="Description" 
                    class="form-control" <?php echo error_field('description', $errors); ?>
                    ><?php echo isset($pdt)?$pdt->getDescription() :'' ?></textarea>
                <textarea type="text" name="product[tags]" placeholder="Tags if more than 1 seperate with ','" 
                    class="form-control" <?php echo error_field('tags', $errors); ?> 
                        style="margin-top:10px;"><?php echo isset($pdt)?$pdt->getTags() :'' ?></textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-danger float-right" type="submit" style="margin-right:20px;" 
                    name="cancel" value="cancel">Cancel</button>
                <button type="submit" style="margin-left:20px;"
                    <?php
                        if($action ==='add'):
                    ?>
                        class="btn btn-success" 
                    <?php
                        elseif($action ==='edit'):
                    ?>
                        class="btn btn-success"
                    <?php
                        endif;
                    ?>
                    name="<?php echo $action ?>" 
                    value="<?php echo $action ?>">
                    <?php echo ucfirst($action) ?> 
                </button>
            </div>
        </form>
    </div>
</div>
<style>
.errors {
    margin-bottom: 20px;
}
.errors li {
    color: red;
}
</style>
