<div class="col-8">
<?php
    if(array_key_exists('cart', $_SESSION) && (Cart::count() > 0)):?>
    <h1 class="text-center">Cart details</h1> 
        <hr />
       <h3 class="text-right"> Total<?php echo ' '.Cart::total() ?> </h3>
            <div class="col-9 offset-2">
                <ul class="list-group"> 
                    <?php foreach($products as $product):?>
                        <li class="list-group-item">
                            <span class="text-monospace" style="margin-right:0px;margin-left:15px;">
                                <p><?php echo Helper::escape($product->getName()) ?></p>
                                <p><?php echo Helper::escape($product->getDescription())?></p>
                            </span>
                                <a class="btn btn-outline-danger float-right"  type="button"
                                    href="<?php echo Helper::createLink('cart', 
                                        ['id' => $product->getId(), 'cart' => 'delete']);?>"
                                            alt="remove from cart" class="card-link">X</a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
<?php 
    else:?>
        <h1 class="text-center"> Cart Empty </h1>
<?php 
    endif;
?>
</div>