<div class="col-md-8">
    <h1 class="text-center"> Shop Centre</h1>
        <hr>
    <div class="col-md-10 offset-md-1">
        <div class="card-group">
            <div class=" card">
                <div class="card-body">
                    <h4 class="text-center card-title">My Store</h4>
                        <p class="card-text">
                            number of items for sale:
                        </p>
                        <p class="card-text">
                            number of int
                        </p>
                        <p class="card-text">
                            number of int
                        </p>
                        <a class="btn btn-outline-success float-left"
                            role="button" href="<?php echo Helper::createLink('dash',['list'])?>">View Uploads</a>
                        <a class="btn btn-success float-right"
                            role="button" href="<?php echo Helper::createLink('add-edit')?>">Add Item</a>
                </div>
            </div>
        </div>
    </div>
</div>
