<div class="col-8">
     <h1 class="text-center">Product details</h1> 
            <hr />
    <div class="col-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"><?php echo Helper::escape($product->getName()) ?></h4>
                <h6 class="text-muted card-subtitle mb-2"><?php echo Helper::escape($product->getPrice()) ?></h6>
                <p class="card-text"><?php echo Helper::escape($product->getDescription()) ?></p>
                <p class="text"><?php echo Helper::escape($product->getTags())?></p> 
                <?php
                    echo Cart::button($product->getId());
                ?>
                <a href="<?php echo Helper::createLink('list');?>" class="card-link">Back</a>
            </div>
        </div>
    </div>
</div>