<div data-ride="carousel" class="carousel slide" id="carousel-1">
    <div role="listbox" class="carousel-inner">
        <div class="carousel-item active">
            <div class="row">
                <div class="col">
                    <div class="jumbotron">
                        <h1>Heading text</h1>
                        <p>Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                        <p><a class="btn btn-primary" role="button" href="#">Learn more</a></p>
                    </div>
                </div>
            </div></div>
        <div class="carousel-item">
            <div class="jumbotron">
                <h1>Heading text</h1>
                <p>Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                <p><a class="btn btn-primary" role="button" href="#">Learn more</a></p>
            </div>
        </div>
        <div class="carousel-item">
        <div class="jumbotron">
                <h1>Heading text</h1>
                <p>Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                <p><a class="btn btn-primary" role="button" href="#">Learn more</a></p>
            </div>
        </div>
    </div>
    <div><a href="#carousel-1" role="button" data-slide="prev" class="carousel-control-prev"><span aria-hidden="true" class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a><a href="#carousel-1" role="button" data-slide="next" class="carousel-control-next"><span aria-hidden="true" class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a></div>
    <ol
        class="carousel-indicators">
        <li data-target="#carousel-1" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-1" data-slide-to="1"></li>
        <li data-target="#carousel-1" data-slide-to="2"></li>
        </ol>
</div>