<div class="row">
    <div class="col-12 offset-lg-0">
        <h1 class="text-center">Welcome User</h1>
    </div>
    <div class="col-6 offset-3">
        <form target="_self" method="post">
            <div class="form-group"><input type="text" placeholder="Name"  name="user[name]" class="form-control" /></div>
            <div class="form-group"><input type="email" name="user[email]" placeholder="Email" class="form-control"  /></div>
            <div class="form-group"><input type="password" name="user[password]" placeholder="Password" class="form-control form-control"  />
            <input type="password" name="user[passwordRepeat]" placeholder="Repeat Password" class="form-control form-control" style="  margin-top:10px;" /></div>
            <div class="form-group"><button class="btn btn-danger float-right" type="submit" style="margin-left:10px;" name="cancel" value="cancel">Cancel</button>
            <button class="btn btn-success float-right" type="submit" style="margin-right:20px;" name="register" value="register">Register / Login</button></div>
            <br /><hr /><div class="form-group">
    <button class="btn btn-outline-secondary" type="submit" name="forgot" value="register">Lost / Reset Password</button></div>
        </form>
    </div>
</div>

<?php

